version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: covid19
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
  ingestion:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
